version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - database
    labels:
      - "traefik.http.routers.blog-php.rule=Host(`blog-php.victork.fr`)"
      - "traefik.http.routers.blog-php-tls.tls.domains[0].main=blog-php.victork.fr"
      - "traefik.http.routers.blog-php-tls.tls.domains[0].sans=blog-php-*.victork.fr"
      - "traefik.http.routers.blog-php.tls=true"
    networks:
      - traefik
  database:
    restart: unless-stopped
    build:
      context: ./sql
    volumes:
      - mysql_8.2.0:/var/lib/mysql
    networks:
      - traefik
    ports:
        - '3306:3306'
        - '33060:33060'
  phpmyadmin:
    depends_on:
      - database
    container_name: phpmyadmin-mysql-mysql_8.2.0
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports:
      - '3308:80'
    environment:
      - PMA_HOST=database
    networks:
      - traefik

volumes:
  mysql_8.2.0:
  
networks:
  traefik:
    name: traefik_webgateway
    external: true
  
  
  